competition:
  start:
    position:
      x: 406.0252685546875
      y: 124.70137786865234
      z: 0.7214583158493042
    orientation: 
      x: 0
      y: 0
      z: 0.7071068
      w: 0.7071068
  goal:
    position: 
      x: 136.9810028076172
      y: 209.24661254882812
      z: 0.2214505672454834
    orientation: 
      x: 0
      y: 0
      z: 0.8509035
      w: 0.525322
  traffic_rules: true
  ready_for_ego: false
  town_name: 'Town04'
  spawn_npc:
    n: 50
    w: 50
    s: 123 # seed
