competition:
  start:
    position: 
      x: 73.83619689941406
      y: -146.0133819580078
      z: 0.04000286012887955
    orientation: 
      x: 2.1600606338207966e-06
      y: 8.801134262670446e-05
      z: 0.0730021047153327
      w: 0.9973317827866859
  goal:
    position: 
      x: -233.1313018798828
      y: -94.81763458251953
      z: 0.0012862395960837603
    orientation: 
      x: -3.930206022153003e-05
      y: -7.80764046432297e-05
      z: -0.015550318616533812
      w: 0.9998790826646727
  traffic_rules: true
  ready_for_ego: false
  town_name: 'Town05'
  spawn_npc:
    n: 150
    w: 50
    s: 1 # seed