competition:
  start:
    position: 
      x: -152.083251953125
      y: -154.6916046142578
      z: 0.056813087314367294
    orientation: 
      x: -3.652973147573293e-05
      y: 3.4881855101179284e-05
      z: 0.001272725614095637
      w: 0.9999991888088441
  goal:
    position: 
      x: -184.91590881347656
      y: -110.39464569091797
      z: 0.0014303970383480191
    orientation: 
      x: 0.00013552336434468314
      y: 4.552527913033062e-06
      z: -0.9999915220802147
      w: 0.004115504876434526
  traffic_rules: true
  ready_for_ego: false
  town_name: 'Town05'
  spawn_npc:
    n: 150
    w: 50
    s: 1 # seed