competition:
  start:
    position: 
      x: -41.72
      y: 208.93
      z: 0.001379527966491878
    orientation: 
      x: -5.9916726801633146e-05
      y: 5.469997614848345e-06
      z: 0.9999617630545543
      w: 0.00874464458352526
  goal:
    position: 
      x: 74.82649993896484
      y: -71.84608459472656
      z: 0.0014213371323421597
    orientation: 
      x: -0.0001329669260154812
      y: 0.0001445720074012564
      z: -0.15631111063386005
      w: 0.9877078505869742
  traffic_rules: true
  ready_for_ego: false
  town_name: 'Town03'
  spawn_npc:
    n: 0 # orig: 50
    w: 0 # orig: 50
    s: 1 # seed